var baseUrl = $('#baseUrl').val();
var array = [
	{name: "vehiclecategory", value: baseUrl + "vehicle/categorySubmit"},
	{name: "vehicle", value: baseUrl + "vehicle/vehicleSubmit"},
	{name: "vehicleList", value: baseUrl + "vehicle/vehicleDelete"},
	{name: "vehicle_update", value: baseUrl + "vehicle/vehicleUpdate"},
	{name: "vehicleList", value: baseUrl + "vehicle/vehicleDelete"},
	{name: "vehicle-detail-view", value: baseUrl + "vehicle/vehicleDetails"},
	{name: "drivermaster", value: baseUrl + "driver/driverMasterSubmit"},
	{name: "driverList", value: baseUrl + "driver/driverDelete"},
	{name: "driver_update", value: baseUrl + "driver/driverUpdate"},
	{name: "vendormaster", value: baseUrl + "vendor/addvendor"},
	{name: "vendorList", value: baseUrl + "vendor/vendorDelete"},
	{name: "vendor_update", value: baseUrl + "vendor/vendorUpdate"},
	{name: "useradd", value: baseUrl + "user/adduser"},
	{name: "user_update", value: baseUrl + "user/Userupdate"},
	{name: "userList", value: baseUrl + "user/userDelete"},
	{name: "bookingmaster", value: baseUrl + "booking/addbooking"},
	{name: "booking_update", value: baseUrl + "booking/Bookingupdate"},
	{name: "bookingList", value: baseUrl + "booking/bookingDelete"},
	{name: "passenger-detail-view", value: baseUrl + "booking/passengerList"},
	{name: "customermaster", value: baseUrl + "customer/addcustomer"},
	{name: "customerUpdate", value: baseUrl + "customer/customerUpdate"},
	{name: "customermaster1", value: baseUrl + "customer/addcustomer"},
	{name: "customerUpdate1", value: baseUrl + "customer/customerUpdate"},
	{name: "dutySlip", value: baseUrl + "booking/addDutySlip"},
	{name: "updateDutySlip", value: baseUrl + "booking/updateDuty"},
	{name: "passenger-detail-delete", value: baseUrl + "booking/passengerDelete"},
	{name: "login", value: baseUrl + "login/loginAction"},
	{name: "driverattn", value: baseUrl + "driver/driverAttnSubmit"},
	{name: "holiday", value: baseUrl + "company/addHoliday"},
	{name: "holidayList", value: baseUrl + "company/holidayDelete"},
	{name: "attendanceReport", value: baseUrl + "driver/attnReport"},
	{name: "expensemaster", value: baseUrl + "payment/expenseMasterSubmit"},
	{name: "advancesalarymaster", value: baseUrl + "payment/advancesalaryMasterSubmit"},
	{name: "insertaccount", value: baseUrl + "account/accountSubmit"},
	{name: "updateaccount", value: baseUrl + "account/accountUpdate"},
	{name: "accountList", value: baseUrl + "account/accountDelete"},
	{name: "addamount", value: baseUrl + "account/addAmountSubmit"},
	{name: "addamount", value: baseUrl + "account/addAmountSubmit"},
	{name: "transactionList", value: baseUrl + "account/transactionDelete"},
	{name: "editTransaction", value: baseUrl + "account/transactionEdit"},
	{name: "profit_and_loss", value: baseUrl + "account/profit_and_loss"},
	{name: "journalvoucher", value: baseUrl + "payment/journalentrySubmit"},
	{name: "package", value: baseUrl + "package/addPackage"},
	{name: "package_update", value: baseUrl + "package/updatePackage"},
	{name: "package-List-booking", value: baseUrl + "package/packageListBooking"},
	{name: "addgroup", value: baseUrl + "account/addgroupSubmit"},
	{name: "ledList", value: baseUrl + "account/disableLedger"},
	{name: "grpList", value: baseUrl + "account/disableGroup"},
	{name: "editgroup", value: baseUrl + "account/updateGroup"},
	{name: "invoicePaid", value: baseUrl + "invoice/invoicePaidSubmit"},
	{name: "get-driver-sal", value: baseUrl + "payment/getDriverSal"},
	{name: "sal-paid", value: baseUrl + "payment/salPaid"},
	{name: "category-update", value: baseUrl + "vehicle/categoryUpdate"},
	{name: "categoryList", value: baseUrl + "vehicle/categoryDelete"},
	{name: "vehicle-img-remove", value: baseUrl + "vehicle/vehicleImgDelete"},
	{name: "billpayment", value: baseUrl + "vendor/billPayment"},

	
	
	

	
	
	
];

